### PR TITLE
Execute service-runner.js when forking

### PR DESCRIPTION
**Pull request by arlolra**
/cc @wikimedia/services

### CODE REVIEW

**Comment by arlolra** [comment]
https://phabricator.wikimedia.org/P3127

**Comment by arlolra** [comment]
👎 hold off on merging while I update it

**Comment by d00rman** [comment]
This looks like a no-op to me. If the master process managed to reach this code, what prevents the worker to do the same since a `fork()` replicates the call?

**Comment by arlolra** [comment]
The default value for `exec` is `process.argv[1]`.  This matters when you're using `service-runner` as module, not the bin.

https://nodejs.org/api/cluster.html#cluster_cluster_setupmaster_settings

**Comment by arlolra** [comment]
For example, in https://github.com/wikimedia/restbase/blob/e7fb889ca00efdf320c3b6f968077c26f3f8087f/test/features/metrics.js#L10

you wouldn't want the worker to take the same route to reaching this code.

**Comment by d00rman** [comment]
Ah right, you're addressing the situation where service-runner is used programmatically but the number of workers is non-zero.

**Comment by arlolra** [comment]
Yes, exactly.

**Pull request merged**
