### PR TITLE
Invert logic to match method name, and release v1.1.6

### PR DESCRIPTION
**Pull request by gwicke**

### CODE REVIEW

**Comment by Pchelolo** [comment]
So, no we're defaulting to allowing access right? 

If that's the case - LGTM

**Comment by gwicke** [comment]
This is just reflecting the rename from check() to isAboveLimit(). While both `limitation` and `service-runner` had been updated to the new name, only `limitation` had the return value flipped in line with the name change.

**Comment by Pchelolo** [comment]
:+1:

**Pull request merged**
