### PR TITLE
Fix styles

### PR DESCRIPTION
**Pull request by subbuss**
Fixed some styles, borrowed jscsrc from Parsoid + tweaked it, additional style tweaks.

Additional styles could be enforced later on.

### CODE REVIEW

**Comment by subbuss** [comment]
Let me know if you want those 3 squashed into one. Or, if you want 2nd commit as the first one and the 1st and 3rd squashed into a single followup.

**Comment by gwicke** [comment]
@subbuss, could you rebase this?

**Comment by subbuss** [comment]
done

**Comment by gwicke** [comment]
@subbuss, thank you!

**Pull request merged**
