### PR TITLE
Update README & only use ES6 constructs globally

### PR DESCRIPTION
**Pull request by gwicke**

### CODE REVIEW

**Comment by gwicke** [comment]
@cscott, please have a look.

**Comment by d00rman** [comment]
@gwicke why this change for bluebird?

**Comment by gwicke** [comment]
@d00rman, we have been using bluebird all along, as it is the fastest Promise implementation currently (even on IOJS) & adds some convenient features.

This change mainly avoids setting it as the global Promise implementation, so that users who don't need the extended functionality or performance get a plain ES6 Promise.

**Comment by gwicke** [comment]
@d00rman, here are some benchmarks on iojs 1.1.0:

```
bench doxbee:
 
results for 10000 parallel executions, 1 ms per I/O op
 
file                                     time(ms)  memory(MB)
callbacks-baseline.js                         183       35.77
promises-bluebird-generator.js                217       38.00
promises-bluebird.js                          271       51.88
promises-cujojs-when.js                       335       66.34
promises-tildeio-rsvp.js                      367       87.58
callbacks-caolan-async-waterfall.js           482       88.43
promises-dfilatov-vow.js                      492      114.43
promises-lvivski-davy.js                      542      119.84
promises-calvinmetcalf-lie.js                 631      167.65
generators-tj-co.js                          1048      162.77
promises-obvious-kew.js                      1055      263.37
promises-ecmascript6-native.js               1074      188.40
promises-then-promise.js                     1253      295.41
promises-medikoo-deferred.js                 1483      261.10
observables-Reactive-Extensions-RxJS.js      2308      355.62
promises-kriskowal-q.js                      8100      707.28
observables-baconjs-bacon.js.js             21858      875.86
observables-caolan-highland.js             102176      615.52
 
Platform info:
Linux 3.16.0-4-amd64 x64
Node.JS 1.1.0
V8 4.1.0.14
Intel(R) Core(TM) i7-4600U CPU @ 2.10GHz × 4
 
bench parallel:
 
results for 10000 parallel executions, 1 ms per I/O op
 
file                                time(ms)  memory(MB)
promises-bluebird.js                     419      106.14
promises-bluebird-generator.js           462      110.55
promises-cujojs-when.js                  606      160.80
promises-tildeio-rsvp.js                 701      215.48
promises-dfilatov-vow.js                 715      201.56
promises-lvivski-davy.js                 965      273.32
callbacks-caolan-async-parallel.js       992      222.97
callbacks-baseline.js                   1089       42.74
promises-calvinmetcalf-lie.js           1142      374.52
promises-ecmascript6-native.js          2420      541.53
promises-then-promise.js                2919      692.91
promises-medikoo-deferred.js            2943      543.63
promises-obvious-kew.js                 4920      965.10
 
Platform info:
Linux 3.16.0-4-amd64 x64
Node.JS 1.1.0
V8 4.1.0.14
Intel(R) Core(TM) i7-4600U CPU @ 2.10GHz × 4
```

**Pull request merged**
