### PR TITLE
Missed one

### PR DESCRIPTION
**Pull request by arlolra**
/cc @gwicke

### CODE REVIEW

**Comment by subbuss** [comment]
Can you update the commit message?

I use this criteria for commit message headlines: "git log --oneline" or "deploy summaries on wikis" should make sense.

**Comment by gwicke** [comment]
@arlolra, could you also prepare a version bump to 2.0.1?

**Comment by arlolra** [comment]
@subbuss @gwicke how's that?

**Comment by Pchelolo** [comment]
👍

**Pull request merged**
