### PR TITLE
Don't normalize prometheus label values

### PR DESCRIPTION
**Pull request by ottomata**
Slight refactor of prometheus label names initialization.  Should
be a no-op that just makes the code a bit more readable.

### CODE REVIEW

**Review by shdubsh — APPROVED** [review]
LGTM, Thanks!

**Comment by ottomata** [comment]
@Pchelolo realized we need this too.  Can we merge this and make a new service-runner release (2.8.4?) and then I can patch service-template-node to use that?

**Comment by Pchelolo** [comment]
Released and published.

**Comment by ottomata** [comment]
Thank you!

**Pull request merged**
