### PR TITLE
Rename log_components to sampled_levels; release v1.2.0

### PR DESCRIPTION
**Pull request by gwicke**

### CODE REVIEW

**Comment by Pchelolo** [comment]
:+1:

**Comment by gwicke** [comment]
Should be deployed with https://github.com/wikimedia/hyperswitch/pull/31.

Config change to leverage this prepared at https://gerrit.wikimedia.org/r/#/c/280711/.

**Comment by Pchelolo** [comment]
Published as `service-runner@1.2.0`

**Comment by d00rman** [comment]
What was the rationale for this rename? Asking out of curiosity since nothing else was changed, and this is a breaking change which needed a minor bump.

**Pull request merged**
