### PR TITLE
Use default cluster scheduling policy & release v2.0.10

### PR DESCRIPTION
**Pull request by gwicke**

### CODE REVIEW

**Comment by Pchelolo** [comment]
@gwicke So, you've finally decided going for it? Did you do some perf testing? Is the difference noticeable?

**Comment by gwicke** [comment]
@Pchelolo: It's definitely noticeable in local testing with wrk, where I would otherwise occasionally see one or two workers take all the load (persistent connections). We are seeing similar load imbalances in prod, which this should help improve on.

**Comment by Pchelolo** [comment]
@gwicke ok, let's give it a try then. merging

**Comment by gwicke** [comment]
Effect on RB heap usage in prod: 

image

It's clear that load is now more evenly distributed across workers. The effect on client observed latency seems to be small for RB. It might be bigger for CPU-intensive services like Parsoid.

**Pull request merged**
