### PR TITLE
Switch prometheus timings to seconds #2

### PR DESCRIPTION
**Pull request by akosiaris**
This effectively reverts commit
844fe44bb79b08bbc307534ddc72399c46776158, whose parent was mistakenly
pushed instead of being merged as a PR. Below is the original PR

Date.now() returns milliseconds and startTime is assumed to be a
Date.now() call result too.

In prometheus land, the rule is to always use seconds[1] and not have to
care about the prefixes of units[2]

The vast majority of metric names out there follow that pattern. Instead
of diverging, causing confusions to developers who need to adapt their
heads around naming metric differently as well as setting histogram
buckets differently, conform to the status quo and divide by 1000.
Precision won't be lost as we just move around the decimal separator.

This is a breaking change for applications/services that have migrated
to prometheus, so bump to 3.1.0. Charts and statistics might have to be
updated as well as dashboards.

[1] https://prometheus.io/docs/instrumenting/writing_exporters/#naming
[2] https://www.robustperception.io/who-wants-seconds

### CODE REVIEW

**Comment by akosiaris** [comment]
Let's try to do #244 correctly now :-)

**Comment by Pchelolo** [comment]
Makes sense to me. I think event services maintained by @ottomata are the major users of native prometheus, so I'll let him have a chance to say something

**Comment by mszabo-wikia** [comment]
Would it make sense to backport this to v2.8.x? I see some of the services are not yet on v3 ;d

**Comment by akosiaris** [comment]
> Would it make sense to backport this to v2.8.x? I see some of the services are not yet on v3 ;d

I don't think there is such a versioning policy (e.g. supporting a prior version), at least I 've never read or heard about any. If there is, we could do that, but otherwise, just bump projects to v3 ?

**Comment by mszabo-wikia** [comment]
@akosiaris yeah, but it requires migrating metrics invocations to the new API, which seems to be the main reason why most/all wikimedia node services remain on 2.8.x

**Comment by akosiaris** [comment]
@ottomata gave his thumbs up at https://phabricator.wikimedia.org/T222795#7578389 so this can be merged.

**Comment by akosiaris** [comment]
> @akosiaris yeah, but it requires migrating metrics invocations to the new API, which seems to be the main reason why most/all wikimedia node services remain on 2.8.x

Could be, but on the other both 2.9 and 3.0 were released on Sept 15th. My money is more on the "most wikimedia nodejs services aren't even aware that 3.0 exists" than on the "they will stall upgrading this because it might require some work".

**Pull request merged**
