### PR TITLE
Docker: don't capture git-review output

### PR DESCRIPTION
**Pull request by Pchelolo**
Sometimes `git review` needs user interaction, for example if the gerrit username/password is not set up, or if for some reason it's trying to submit several changes. In that case if we capture the output for the user it looks like the script is stuck. At least with this user would be able to interact with git-review and figure out what's the problem.

Bug: https://phabricator.wikimedia.org/T141917
cc @wikimedia/services

### CODE REVIEW

**Comment by d00rman** [comment]
How about we make it dependant on whether the user specified the `--verbose` cmdline arg? Without that, the context may not be clear enough.

**Comment by Pchelolo** [comment]
@d00rman The context would be pretty clear, it will print. `Submitting your changes for review` and then whatever git-review output would be, so it would be either success message, or a prompt with a question to the user. 

These question asking situation indicates that something is configured incorrectly, so asking a use to provide yet another flag is imho an overkill as you would first run without a flag and see how the process gets stuck for no reason - start waiting and loose time before you understand to kill the process and restart with  `--verbose`

**Comment by Pchelolo** [comment]
Introduced one more improvement in the script - docker version check was done incorrectly before on linux

**Comment by d00rman** [comment]
Published as [v2.0.7](https://github.com/wikimedia/service-runner/tree/v2.0.7)

**Pull request merged**
