### PR TITLE
Don't parse cli args in worker

### PR DESCRIPTION
**Pull request by arlolra**
It's incompatible with using this as a library.

### CODE REVIEW

**Comment by Pchelolo** [comment]
gr8! Thank you @arlolra

**Comment by arlolra** [comment]
Can I bump the version and release this?

**Comment by Pchelolo** [comment]
@arlolra sure if it's urgent

**Comment by arlolra** [comment]
It's blocking https://gerrit.wikimedia.org/r/c/mediawiki/services/parsoid/+/512064

**Comment by Pchelolo** [comment]
Done in #215

**Pull request merged**
